/* eslint-disable */
export enum UserActionTypes {
  ACTION_LOGIN = 'ACTION_LOGIN',
  ACTION_GET_USER_INFO = 'ACTION_GET_USER_INFO',
  ACTION_SET_USER_INFO = 'ACTION_SET_USER_INFO',
  ACTION_LOGIN_OUT = 'ACTION_LOGIN_OUT',
  ACTION_RESET_TOKEN = 'ACTION_RESET_TOKEN'
}
