/* eslint-disable */
export enum GoodsMutationTypes {
  ADD_GOODS = 'ADD_GOODS',
  REMOVE_GOODS = 'REMOVE_GOODS',
  INCREMENT_GOODS_COUNT = 'INCREMENT_GOODS_COUNT',
  DECREMENT_GOODS_COUNT = 'DECREMENT_GOODS_COUNT',
  EMPTY_CART = 'EMPTY_CART',
  INIT_CART = 'INIT_CART'
}
